config/routes.rb
      resources :purchases,       :path => "/fundamental/characters/:character_id/purchases",       :module => 'shop',       :controller => 'purchases',:only => [:index]
      resources :standard_assignments, :path => "/fundamental/characters/:character_id/standard_assignments",          :module => 'assignment',   :only => [:index]
      resource  :special_assignment,   :path => "/fundamental/characters/:character_id/special_assignment",            :module => 'assignment',   :only => [:show]

      resource  :shop_account,    :path => "/fundamental/characters/:character_id/shop_account",    :module => 'shop',       :controller => 'accounts', :only => [:show]

      resources :artifacts,       :path => "/map/regions/:region_id/artifacts",                     :module => 'fundamental'
      resources :artifacts,       :path => "/map/locations/:location_id/artifacts",                 :module => 'fundamental'

      resources :resource_effects, :path => "/fundamental/resource_pools/:resource_pool_id/resource_effects", :module => 'effect',   :only => [:index]
      resources :alliance_resource_effects, :path => "/fundamental/alliances/:alliance_id/alliance_resource_effects", :module => 'effect',   :only => [:index]
    
      resources :construction_effects, :path => "/fundamental/characters/:character_id/construction_effects", :module => 'effect',   :only => [:index]
      resources :alliance_construction_effects, :path => "/fundamental/alliances/:alliance_id/alliance_construction_effects", :module => 'effect',   :only => [:index]


      namespace :messaging do 
        resources :archives do
          resources :entries, :controller => :archive_entries
        end
        resources :outboxes do
          resources :entries, :controller => :outbox_entries
        end
        resources :inboxes do
          resources :entries, :controller => :inbox_entries 
        end
        resources :inbox_entries 
        resources :outbox_entries
        resources :archive_entries
        resources :messages
        resources :jabber_commands
      end
      resources :inboxes,  :path => "/fundamental/characters/:character_id/inboxes",  :module => 'messaging', :only => [:index]            
      resources :outboxes, :path => "/fundamental/characters/:character_id/outboxes", :module => 'messaging', :only => [:index]            
      resources :archives, :path => "/fundamental/characters/:character_id/archives", :module => 'messaging', :only => [:index]            



      namespace :settlement do 
        resources :settlements do 
          resources :slots 
          resources :histories
          resources :incoming_trading_carts,  :only => [ :index ]
          resources :outgoing_trading_carts,  :only => [ :index ]

          # resources :queues, :module => 'construction'
        end
        resources :slots 
        resources :histories
      end

      resources :queues, :path => "/settlement/settlements/:settlement_id/construction_queues", :module => 'construction'            
      resources :queues, :path => "/settlement/settlements/:settlement_id/training_queues", :module => 'training'            

      resources :settlements, :path => "/map/locations/:location_id/settlements", :module => 'settlement'            
      resources :settlements, :path => "/map/regions/:region_id/settlements", :module => 'settlement'            


      namespace :military do 
        resources :armies do
          resources :army_details
           get 'livesearch',  :on => :collection
        end
        resources :army_details
        resources :battles do
          resources :battle_rounds 
          resources :battle_participants 
          resources :battle_factions
        end
        resources :battle_factions do
          resources :battle_participants 
        end
        resources :battle_participants 

        resources :battle_character_results
        resources :battle_participant_results 
        resources :battle_faction_results
        resources :battle_rounds
      end

      resources :armies, :path => "/map/regions/:region_id/armies", :module => 'military'            
      resources :armies, :path => "/map/locations/:location_id/armies", :module => 'military'            
      resources :armies, :path => "/fundamental/characters/:character_id/armies", :module => 'military'            
      resources :armies, :path => "/fundamental/alliances/:alliance_id/armies", :module => 'military'            

      resources :battles, :path => "/map/regions/:region_id/battles", :module => 'military'            
      resources :battles, :path => "/map/locations/:location_id/battles", :module => 'military'            

      namespace :map do 
        
        resources :nodes do 
          resources :regions 
        end
        resources :subtrees, :only => [ :show ]
        resource :area, :only => [ :show ]
        
        resources :regions do
          resources :locations
#         resources :armies, :module => 'military'             # doesn't work, since it looks for Map::Military::ArmiesController instead of Military::ArmiesController
#         resources :slots,  :controller => 'locations', :only => [ :show, :index ]  
        end
        resources :locations do
        end
        
        match 'regions/:region_id/slots',       :via => :get, :controller => 'locations', :action => 'index'
        match 'regions/:region_id/slots/:slot', :via => :get, :controller => 'locations', :action => 'show'
        match 'regions/:region_id/fortress',    :via => :get, :controller => 'locations', :action => 'show', :slot => 0
      end

      namespace :event do 
        resources :events
      end

      namespace :action do  
        namespace :military do 
          resources :move_army_actions          
          resources :create_army_actions         
          resources :change_army_actions         
          resources :reinforce_army_actions         
          resources :cancel_move_army_actions   
          resources :attack_army_actions       
          resources :retreat_army_actions      
          resources :found_outpost_actions,   :only => [ :create ] 
          resources :found_home_base_actions, :only => [ :create ] 
        end 
        namespace :fundamental do
          resources :auto_join_alliance_actions,                :only => [ :create ]    
          resources :join_alliance_actions,                     :only => [ :create ]    
          resources :leave_alliance_actions    
          resources :create_alliance_actions    
          resources :kick_alliance_member_actions,              :only => [ :create ]
          resources :change_alliance_auto_join_setting_actions, :only => [ :create ]
          resources :change_alliance_description_actions,       :only => [ :create ]
          resources :alliance_leader_vote_actions,              :only => [ :create ]
          resources :diplomacy_relation_actions,                :only => [ :create ]
          resources :change_character_description_actions,      :only => [ :create ]
          resources :send_alliance_application_actions,         :only => [ :create ]
          resources :change_avatar_actions,                     :only => [ :index, :create ]
          resources :change_character_notified_rank_actions,    :only => [ :create ]    
          resources :change_character_name_actions,             :only => [ :create ]
          resources :change_character_same_ip_actions,          :only => [ :create ]
          resources :change_character_gender_actions,           :only => [ :create ]
          resources :change_character_password_actions,         :only => [ :create ]
          resources :track_character_conversions,               :only => [ :create ]
          resources :trade_resources_actions,                   :only => [ :create ]
          resources :send_like_actions,                         :only => [ :create ]
          resources :send_dislike_actions,                      :only => [ :create ]
          resources :speedup_artifact_initiation_actions,       :only => [ :create ]
          resources :displayed_premium_expiration_actions,      :only => [ :create ]
          resources :user_content_report_actions,               :only => [ :create ]
          resources :connect_facebook_actions,                  :only => [ :create ]    
        end
        namespace :construction do
          resources :finish_job_actions    
        end
        namespace :messaging do
          resources :archive_entries_actions#, :only => [ :create]
        end
        namespace :trading do 
          resources :trading_carts_actions 
          resources :speedup_trading_carts_actions,    :only => [ :create ]
        end 
        namespace :training do
          resources :speedup_job_actions    
        end
        namespace :assignment do
          resources :speedup_standard_assignment_actions, :only => [ :create ]
          resources :start_standard_assignment_actions, :only => [ :create ]
          resources :speedup_special_assignment_actions, :only => [ :create ]
          resources :start_special_assignment_actions, :only => [ :create ]
        end
        namespace :settlement do
          resources :change_tax_rate_actions, :only => [ :create ] 
          resources :abandon_outpost_actions, :only => [ :create ]
          resources :change_settlement_name_actions, :only => [ :create ]
          resources :redeem_slot_bubble_actions, :only => [ :create ]
          resources :move_settlement_to_region_actions, :only => [ :create ]
        end
        namespace :tutorial do
          resources :check_quest_actions,                 :only => [ :create ]    
          resources :mark_quest_displayed_actions,        :only => [ :create ]    
          resources :mark_quest_reward_displayed_actions, :only => [ :create ]    
          resources :redeem_rewards_actions,              :only => [ :create ]    

app/models/action/military.rb
module Action::Military
  def self.table_name_prefix
    'action_military_'
  end
end

app/models/action/military/attack_army_action.rb
class Action::Military::AttackArmyAction < ActiveRecord::Base
end

app/models/military.rb
module Military
  def self.table_name_prefix
    'military_'
  end
end

app/models/military/battle_character_result.rb
class Military::BattleCharacterResult < ActiveRecord::Base

  belongs_to  :battle,     :class_name => "Military::Battle",        :foreign_key => "battle_id",     :inverse_of => :character_results
  belongs_to  :faction,    :class_name => "Military::BattleFaction", :foreign_key => "faction_id"
  belongs_to  :character,  :class_name => "Fundamental::Character",  :foreign_key => "character_id",  :inverse_of => :battle_results

end

app/controllers/action/military/attack_army_actions_controller.rb
class Action::Military::AttackArmyActionsController < ApplicationController
  layout 'action'

  before_filter :authenticate

  # POST /action/military/attack_army_actions
  # POST /action/military/attack_army_actions.json
  def create
    Military::Army.transaction do  
      attacker = Military::Army.find(params[:action_military_attack_army_action][:attacker_id])
      defender = Military::Army.find(params[:action_military_attack_army_action][:defender_id])
      
      attacker.lock!
      defender.lock!
    
      raise ForbiddenError.new('tried to attack army in different location')    unless attacker.location_id == defender.location_id
      raise ForbiddenError.new('tried to attack with foreign army')             unless attacker.owner_id == current_character_id
      raise ForbiddenError.new('tried to attack own army')                      if attacker.owner_id == defender.owner_id
      raise ForbiddenError.new('attacker is already fighting')                  if attacker.fighting? && !attacker.garrison?  # garrison may attack another army! (presently, because there's no wegerecht)
      raise ForbiddenError.new('attacker army is empty')                        if attacker.empty?
      raise ForbiddenError.new('attacker is currently suspended')               if attacker.suspended?
      raise ForbiddenError.new('defender is currently under attack protection') if defender.protected?

      attacker.consume_ap         unless attacker.garrison?                                    # raises a BadAccessError if no aps are available
      Military::Battle.start_fight_between(attacker, defender)     # creates and returns battle, or returns nil, if army was overrun
    end
    
    respond_to do |format|
      format.json { render json: {}, status: :ok }
    end
  end
end

app/controllers/action/military/cancel_move_army_actions_controller.rb
class Action::Military::CancelMoveArmyActionsController < ApplicationController
  layout 'action'
  
  before_filter :authenticate


  # GET /action/military/move_army_actions/new
  # GET /action/military/move_army_actions/new.json
  def new
    respond_to do |format|
      format.json { render json: { :army_id => nil} }
    end
  end

  # POST /action/military/move_army_actions
  # POST /action/military/move_army_actions.json
  def create
    army = Military::Army.find_by_id(params[:action_military_cancel_move_army_action][:army_id])
    raise BadRequestError.new('army does not exist') if army.blank?
    raise BadRequestError.new('no movement command found') if army.movement_command.blank?
    
    role = army.owned_by?(current_character_id) ? :owner : :character # TODO: staff / admin
    
    raise ForbiddenError.new('tried to cancel command of foreign army') unless role === :owner || role === :staff || role === :admin
    
    if army.movement_command.event.blank?   # don't crash, a cancel action might be the cure for a missing entry in the event table
      logger.error "Could not find an event for movement command #{army.movement_command.id}: " + army.movement_command.inspect + ' / ' + army.inspect
    else 
      army.movement_command.event.destroy
    end
    army.movement_command.destroy
    
    army.target_location_id = nil
    army.target_region_id = nil
    if army.mode === Military::Army::MODE_MOVING  # 1: moving?
      army.mode = Military::Army::MODE_IDLE
    end
    army.target_reached_at = nil
    army.attack_protection_ends_at = nil

    if !army.save 
      raise BadRequestError.new('could not save the new state of the army')
    end

    respond_to do |format|
      format.html { redirect_to new_action_military_cancel_move_army_action_path, notice: 'Move army action was successfully executed.' }
      format.json { render json: {}, status: :created }
    end
  end
  
end

app/controllers/action/military/change_army_actions_controller.rb
class Action::Military::ChangeArmyActionsController < ApplicationController
  layout 'action'
  
  before_filter :authenticate

  # POST /action/military/create_army_actions
  # POST /action/military/create_army_actions.json
  def create
    @action = params[:action_military_change_army_action]
    
    location = Map::Location.find(@action[:location_id])
    raise BadRequestError.new('location not found') if location.nil?
    raise BadRequestError.new('not owner of garrison army') unless location.owner == current_character

    garrison_army = location.garrison_army
    raise BadRequestError.new('garrison army not found') if garrison_army.nil?
    raise BadRequestError.new('not owner of garrison army') unless garrison_army.owner == current_character
    
    visible_army = Military::Army.find(@action[:visible_army_id])
    raise BadRequestError.new('army at settlement not found') if visible_army.nil?
    raise BadRequestError.new('not owner of visible army') unless visible_army.owner == current_character

    raise BadRequestError.new('settlement at location is not home of army') unless visible_army.home == location.settlement

    raise ForbiddenError.new('garrison is not idle')   unless garrison_army.mode == Military::Army::MODE_IDLE
    raise ForbiddenError.new('garrison is fighting')   unless garrison_army.battle_id.nil?

    raise ForbiddenError.new('army is not idle')   unless visible_army.mode == Military::Army::MODE_IDLE
    raise ForbiddenError.new('army is fighting')   unless visible_army.battle_id.nil?
    
    raise ForbiddenError.new('army is not at location of garrison')   unless visible_army.location_id == garrison_army.location_id

    
    units_to_add = {}
    units_to_reduce = {}
    
    unit_sum_to_add = 0
        
    GameRules::Rules.the_rules.unit_types.each do | unit_type |
      quantity = @action[unit_type[:db_field]].to_i      
      if quantity > 0
        units_to_add[unit_type[:db_field]] = quantity
      elsif quantity < 0
        units_to_reduce[unit_type[:db_field]] = -quantity
      end
      unit_sum_to_add += quantity
    end
    
    raise BadRequestError.new('not enough units in visible army') unless visible_army.contains?(units_to_reduce)
    raise BadRequestError.new('not enough units in garrison army') unless garrison_army.contains?(units_to_add)
    
    raise BadRequestError.new('not enough space in visible army') unless visible_army.can_receive?(unit_sum_to_add)    
    raise BadRequestError.new('not enough space in garrison army') unless garrison_army.can_receive?(-unit_sum_to_add)
    
    Military::Army.transaction do
      garrison_army.reduce_units(@action)
      visible_army.add_units(@action)
    end
    
    visible_army.destroy if visible_army.empty?

    respond_to do |format|
      format.html { redirect_to action_path, notice: 'Change army action was successfully executed.' }
      format.json { render json: {}, status: :created }
    end
  end
end

app/views/military/battle_participant_results/_form.html.erb
<%= form_for(@military_battle_participant_result) do |f| %>
  <% if @military_battle_participant_result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@military_battle_participant_result.errors.count, "error") %> prohibited this military_battle_participant_result from being saved:</h2>

      <ul>
      <% @military_battle_participant_result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :battle_id %><br />
    <%= f.number_field :battle_id %>
  </div>
  <div class="field">
    <%= f.label :round_id %><br />
    <%= f.number_field :round_id %>
  </div>
  <div class="field">
    <%= f.label :army_id %><br />
    <%= f.number_field :army_id %>
  </div>
  <div class="field">
    <%= f.label :battle_faction_result_id %><br />
    <%= f.number_field :battle_faction_result_id %>
  </div>
  <div class="field">
    <%= f.label :retreat_tried %><br />
    <%= f.check_box :retreat_tried %>
  </div>
  <div class="field">
    <%= f.label :retreat_succeeded %><br />
    <%= f.check_box :retreat_succeeded %>
  </div>
  <div class="field">
    <%= f.label :kills %><br />
    <%= f.number_field :kills %>
  </div>
  <div class="field">
    <%= f.label :experience_gained %><br />
    <%= f.number_field :experience_gained %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/military/battle_participant_results/edit.html.erb
<h1>Editing military_battle_participant_result</h1>

<%= render 'form' %>

<%= link_to 'Show', @military_battle_participant_result %> |
<%= link_to 'Back', military_battle_participant_results_path %>

app/views/military/battle_participant_results/index.html.erb
<h1>Listing military_battle_participant_results</h1>

<table>
  <tr>
    <th>Battle</th>
    <th>Round</th>
    <th>Participant</th>
    <th>Army</th>
    <th>Battle faction result</th>
    <th>Retreat tried</th>
    <th>Retreat succeeded</th>
    <th>Kills</th>
    <th>Experience gained</th>
<% Military::BattleParticipantResult.new.attributes.each do |attribute, value| 
  if attribute.start_with? 'unit_' %>
    <th><%= attribute %></th>
<%end
end %>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @military_battle_participant_results.each do |military_battle_participant_result| %>
  <tr>
    <td><%= military_battle_participant_result.battle_id %></td>
    <td><%= military_battle_participant_result.round_id %></td>
    <td><%= military_battle_participant_result.participant_id %></td>
    <td><%= military_battle_participant_result.army_id %></td>
    <td><%= military_battle_participant_result.battle_faction_result_id %></td>
    <td><%= military_battle_participant_result.retreat_tried %></td>
    <td><%= military_battle_participant_result.retreat_succeeded %></td>
    <td><%= military_battle_participant_result.kills %></td>
    <td><%= military_battle_participant_result.experience_gained %></td>
<% military_battle_participant_result.attributes.each do |attribute, value| 
  if attribute.start_with? 'unit_' %>
    <td><%= value %></td>
<%end
end%>
    <td><%= link_to 'Show', military_battle_participant_result %></td>
    <td><%= link_to 'Edit', edit_military_battle_participant_result_path(military_battle_participant_result) %></td>
    <td><%= link_to 'Destroy', military_battle_participant_result, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Battle participant result', new_military_battle_participant_result_path %>

app/views/military/battle_participant_results/new.html.erb
<h1>New military_battle_participant_result</h1>

<%= render 'form' %>

<%= link_to 'Back', military_battle_participant_results_path %>

app/views/military/battle_participant_results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Battle:</b>
  <%= @military_battle_participant_result.battle_id %>
</p>

<p>
  <b>Round:</b>
  <%= @military_battle_participant_result.round_id %>
</p>

<p>
  <b>Army:</b>
  <%= @military_battle_participant_result.army_id %>
</p>

<p>
  <b>Battle faction result:</b>
  <%= @military_battle_participant_result.battle_faction_result_id %>
</p>

<p>
  <b>Retreat tried:</b>
  <%= @military_battle_participant_result.retreat_tried %>
</p>

<p>
  <b>Retreat succeeded:</b>
  <%= @military_battle_participant_result.retreat_succeeded %>
</p>

<p>
  <b>Kills:</b>
  <%= @military_battle_participant_result.kills %>
</p>

<p>
  <b>Experience gained:</b>
  <%= @military_battle_participant_result.experience_gained %>
</p>


<%= link_to 'Edit', edit_military_battle_participant_result_path(@military_battle_participant_result) %> |
<%= link_to 'Back', military_battle_participant_results_path %>